name: Upclear DevExtreme package v1

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build devextreme repo
        run: |
          pnpm test -d artifacts || pnpm run all:build

      - name: Copy build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devextreme-npm-packages
          path: ./artifacts/npm/devextreme-*.tgz
          retention-days: 1
