name: Upclear DevExtreme package v1

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Using Node 20 instead of 18

      - name: Clean up node_modules
        run: rm -rf node_modules

      - name: Install dependencies using npm
        run: npm install --legacy-peer-deps

      - name: Debug - Show installed packages
        run: npm list --depth=0

      - name: Debug - Show available scripts
        run: npm run

      - name: Build devextreme repo
        run: npm run all:build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: devextreme-npm-packages
          path: ./artifacts/npm/devextreme-*.tgz
          retention-days: 1
